# Generated by Django 5.1.6 on 2025-03-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='qty',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
    ]
